### PR TITLE
[No-Merge] [WIP] [Qt] Implement Multiple Signatures UI

### LINKED ISSUE #12: MultiSig UI

### PR DESCRIPTION
**Pull request by empinel**
### What is the purpose of this pull request (PR)?

To port the Silk MultiSig Functionality to DarkSilk

**DO NOT MERGE, KEPT FOR RECORD KEEPING AND VIEWING FOR NOW**

#### Was this PR tested and how? (If testing is not needed, please explain why)

Tested on Ubuntu 16.04 LTE although it does have major bugs that need addressal

#### Does this PR resolve an open issue (reference issue #)?

If done, then it will fix #12

### CODE REVIEW

**Comment by GregoryBetz** [comment]
Before making a pull request please make sure there are absolutely no errors of any kind. We cannot merge code into master that will then break master.

**Comment by empinel** [comment]
There is a tag (Work In Progress), and this wasn't designed to be merged

**Comment by AmirAbrams** [comment]
Did you try this:
`uint256 blockHash = uint256("0");`

**Comment by empinel** [comment]
I have it running on my machine back at home, will let you know later

**Comment by empinel** [comment]
This entire thing got screwed worse than broken Ikea furniture

**Pull request closed without merging**
